### ISSUE TITLE
Improve panning behavior on mobile

### ISSUE THREAD

**Issue by shafy** [mapzy/mapzy#26]
Currently, you can pan the map with one finger on mobile devices. This is not good because if the map is full-width, you get stuck on a mobile website.

We should disable one finger panning and only allow two finger panning.

**Comment by sagzy** [comment]
Thanks @shafy! I continued our scrolling discussion on basecamp.

To the name in edit form: even though we don't ask for the name during registration, we could leave it under the account settings no? Then the sign up process is still quick and the user can add it later when they want to. But if you prefer to remove it, also fine with me.
