### ISSUE TITLE
Rename "Install map" to "Embed map"?

### ISSUE THREAD

**Issue by shafy** [mapzy/mapzy#38]
Might be more intuitive what it means? Up for discussion though.

**Comment by sagzy** [comment]
I think "Embed map" sounds a bit more technical so would prefer to keep "Install Map". But I'm fine with both. What do you prefer?

**Comment by shafy** [comment]
I think "Install" kind of implies something more complicated, like installing an app or something. I think people know what embedding means, and it is the closest term I can think of. Therefore, I'd prefer "Embed" for now.

**Comment by sagzy** [comment]
Ok, let's do it then :)
