### ISSUE TITLE
Show multiple simultaneous flash messages below each other

### ISSUE THREAD

**Issue by shafy** [mapzy/mapzy#78]
Currently, if there are two flash messages to be displayed, they are shown on top of each other. We should display them below each other, so that they are all visible.

**Comment by spencerldixon** [comment]
@shafy I'd like to work on this, could you assign me? Also, is there any best example of where you'd get two flash messages happening together?

**Comment by sagzy** [comment]
Hey @spencerldixon, welcome back! :D

Here's one way to replicate the issue:
1) Take any user from the seeds and update its account to inactive: `user = User.first.account.update(status: "inactive")`
2) Log in to the dashboard with this user and you will see an inactive account warning as flash message
3) Then update any location. The success message is a flash message that is hidden by the inactive account warning (if you close the inactive account warning at that step, you'll see the success flash message behind it)
