### ISSUE TITLE
Docker: Read env variables from .env file

### ISSUE THREAD

**Issue by shafy** [mapzy/mapzy#80]
Currently, we pass the env variables in `docker-compose.yml` one by one. This has the advantage that env variables don't need to be defined in an specific file. But it also makes maintenance of the Docker setup more complicated.

I suggest that `docker-compose.yml` should be configured to look for the env variables in a file called `.env`.

**Comment by bmusuko** [comment]
hey can I working on this feature?

**Comment by sagzy** [comment]
Hey @bmusuko, of course! Please go ahead :)

**Comment by bmusuko** [comment]
Hey, I just opened PR to resolve this issue here #91, please kindly check it. Thanks
