### ISSUE TITLE
Add geocoding caching

### ISSUE THREAD

**Issue by shafy** [mapzy/mapzy#85]
The geocoding gem we use has a [caching feature](https://github.com/alexreisner/geocoder#caching) that will help us reduce the number of requests to the Mapbox API. We should implement it.

Note: we cannot use the existing Redis store as cache, as it's used to persist background jobs via Sidekiq. See [here](https://github.com/mperham/sidekiq/wiki/Using-Redis#multiple-redis-instances) for more information.

**Comment by gabrielbaldao** [comment]
I am not sure if you just wanna this setting what i write in #88, could you check or tell me more about it?

**Comment by sagzy** [comment]
Thanks @gabrielbaldao. I responded to you directly on the PR
