### ISSUE TITLE
Fix "Delete" Button

### ISSUE THREAD

**Issue by sagzy** [mapzy/mapzy#90]
In the Location List View (see code [here](https://github.com/mapzy/mapzy/blob/main/app/views/shared/_location_short.html.erb#L42)) and in the Location Detail View (see code [here](https://github.com/mapzy/mapzy/blob/main/app/views/dashboard/locations/show.html.erb)), the deletion button doesn't work anymore.

It's expected to be disabled only when `@map.sync_mode` is on, but it is currently today disabled all the time at the moment.

**Comment by harshxtanwar** [comment]
hello @sagzy can I get assigned to this issue ? I would love to work on it.

**Comment by sagzy** [comment]
Hello @harshxtanwar, sure! Please go ahead

**Comment by shafy** [comment]
Fixed in https://github.com/mapzy/mapzy/pull/113
